cmake_minimum_required(VERSION 4.2)
project(KomisPO)

set(CMAKE_CXX_STANDARD 23)

add_executable(KomisPO entrypoint/main.cpp
        domain/account/Account.cpp
        domain/account/Account.h
        domain/account/CustomerAccount.cpp
        domain/account/CustomerAccount.h
        domain/account/EmployeeAccount.cpp
        domain/account/EmployeeAccount.h
        domain/Vehicle/VehicleStatus.h
        domain/Vehicle/FuelType.h
        domain/Vehicle/Vehicle.cpp
        domain/Vehicle/Vehicle.h
        domain/task/Task.cpp
        domain/task/Task.h
        domain/task/TaskStatus.h
        presentation/cli/menu/Menu.cpp
        presentation/cli/menu/Menu.h
        presentation/cli/console/ConsoleApplication.cpp
        presentation/cli/console/ConsoleApplication.h
        infrastructure/repositories/account/AccountRepositoryImpl.cpp
        infrastructure/repositories/vehicle/VehicleRepositoryImpl.cpp
        infrastructure/repositories/task/TaskRepositoryImpl.cpp
        domain/common/ListTypes.h
        domain/common/Exceptions.h
        domain/repositories/AccountRepository.h
        domain/repositories/VehicleRepository.h
        domain/repositories/TaskRepository.h
        domain/common/DoublyLinkedList.hpp
        domain/vehicle/VehicleData.h
        domain/task/TaskData.h
        app/use_cases/auth/customer/CustomerLoginUsecase.cpp
        app/use_cases/auth/customer/CustomerLoginUsecase.h
        app/use_cases/auth/employee/EmployeeLoginUsecase.cpp
        app/use_cases/auth/employee/EmployeeLoginUsecase.h
        app/use_cases/vehicle/reserve/ReserveVehicleUsecase.cpp
        app/use_cases/vehicle/reserve/ReserveVehicleUsecase.h
        app/services/System.cpp
        app/services/System.h
        infrastructure/repositories/account/AccountRepositoryImpl.h
        infrastructure/repositories/task/TaskRepositoryImpl.h
        infrastructure/repositories/vehicle/VehicleRepositoryImpl.h
        app/use_cases/vehicle/add/AddVehicleUsecase.cpp
        app/use_cases/vehicle/add/AddVehicleUsecase.h
        app/use_cases/vehicle/markReady/MarkVehicleReadyForPickupUsecase.cpp
        app/use_cases/vehicle/markReady/MarkVehicleReadyForPickupUsecase.h
        app/use_cases/vehicle/releaseVehicle/ReleaseVehicleReservationUsecase.cpp
        app/use_cases/vehicle/releaseVehicle/ReleaseVehicleReservationUsecase.h
        app/use_cases/vehicle/remove/RemoveVehicleUsecase.cpp
        app/use_cases/vehicle/remove/RemoveVehicleUsecase.h
        app/use_cases/task/CompleteTaskUsecase.cpp
        app/use_cases/task/CompleteTaskUsecase.h
        tests/fixture.h
        "tests/fixture.cpp"
        app/services/taskGenerator/TaskGenerator.cpp
        app/services/taskGenerator/TaskGenerator.h
        app/services/taskGenerator/taskTemplate.h
        domain/vehicle/VehicleSearchCriteria.h
        app/use_cases/vehicle/search/SearchVehicleUsecase.cpp
        app/use_cases/vehicle/search/SearchVehicleUsecase.h
)
